### ISSUE TITLE
Pull down, don't release, then pull down more - it constantly refreshes

### ISSUE THREAD

**Issue by niftylettuce** [jsdf/react-native-refreshable-listview#32]
This is a bug, e.g.  you pull down a bit, then don't release, then pull down more, it will refresh again and again as you pull down more and more.

**Comment by atom2ueki** [comment]
@niftylettuce 
```javascript
handleScroll(e) {
    var scrollY = e.nativeEvent.contentInset.top + e.nativeEvent.contentOffset.y
    this.lastScrollY = scrollY
    this.lastContentInsetTop = e.nativeEvent.contentInset.top
    this.lastContentOffsetX = e.nativeEvent.contentOffset.x

    if (this.isTouching || (!this.isTouching && !this.props.ignoreInertialScroll)) {
      if (scrollY < -this.props.minPulldownDistance) {
        if (!this.props.isRefreshing) {
          if (this.props.onRefresh) {
            this.props.onRefresh()
          }
        }
      }
    }

    this.props.onScroll && this.props.onScroll(e)
  },
```
the logic is trigger refresh base on distance only currently, and when the time we still touching screen, refresh triggered, however `scrollY` does not reset, that's why it triggered again & again, but I can said that people more suitable on checking `release touch` & `min distance` to trigger the refresh, and also need reset `scrollY` after every refresh

**Comment by jsdf** [comment]
This should be fixed on master now. 



—



Cheers,

James

**Comment by niftylettuce** [comment]
@jsdf it's not.  I can still pull down continously and get the spinner/refresh.  please fix.

**Comment by niftylettuce** [comment]
I am using master in my `package.json` FYI -- so this is definitely a bug still

**Comment by manask88** [comment]
@jsdf ,  any news on when this can be fixed?

**Comment by jsdf** [comment]
I haven't time to work on it. I work on this project in my own time, and I haven't had much of that to spare lately. I'd happily accept a PR to fix it, however.

**Comment by natorojr** [comment]
This may be a duplicate of #16.

@jsdf Seems like you have several open PRs fixing essentially the same issue.
